name: Cross-Compile Rust Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install cross
      run: cargo install cross

    - name: Build with cross
      run: cross build --target ${{ matrix.target }}
      env:
        CROSS_COMPILE: 1

    - name: Artifacts name
      run: echo "ARTIFACT_NAME=$(echo ${{ matrix.target }} | tr '-' '_')" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}_artifact
        path: target/${{ matrix.target }}/debug/
