name: Cross-Compile Rust Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    - name: Install cross
      run: cargo install cross
    - name: Build with cross
      run: cross build --release --target ${{ matrix.target }}
      env:
        CROSS_COMPILE: 1
    - name: Zip the artifact
      run: zip -r ${{ matrix.target }}_artifact.zip target/${{ matrix.target }}/release/
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}_artifact.zip
        path: ${{ matrix.target }}_artifact.zip

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONSGIT }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
        
    - name: List files in the working directory
      run: ls -la ./artifacts/


    # Build the FeedMD CLI utility, and upload to the release that triggered the workflow 
    - name: '📦 Packages Upload'
      run: |
            gh release upload ${{github.event.release.tag_name}} ./artifacts/x86_64-unknown-linux-gnu_artifact.zip       
            gh release upload ${{github.event.release.tag_name}} ./artifacts/aarch64-unknown-linux-gnu_artifact.zip       

